### ISSUE TITLE
about the test

### ISSUE THREAD

**Issue by Usernamezhx** [ethanhe42/resnet-imagenet-caffe#2]
hi yihui-he 
    thanks for your code first. i use your resnet_50.prototxt to train my image sample. I notice that it has no the  the phase : TEST in your resnet_50.prototxt. so that means if i want to test the model. i should use your ResNet-50-test.prototxt . but  it has a little different between the resnet_50.prototxt and ResNet-50-test.prototxt except for the use_global_stats: . can i use the ResNet-50-test.prototxt to test my model that trained by the resnet_50.prototxt？ 
                                                                                                                                        thanks in advance.

**Comment by ethanhe42** [comment]
@Usernamezhx Of course you can.
