### ISSUE TITLE
4个GPU 并没有能够加速计算？

### ISSUE THREAD

**Issue by xoofee** [ethanhe42/resnet-imagenet-caffe#3]
我在本库提供的RESNET-50的LOG中计算了一下，4个GPU计算大约花了2天，BATCH SIZE为32，计算速度大概为1.4 ITERATIONS/SECOND， 相当于45 IMAGES/SECOND。这个速度比我用单块1080TI计算略慢一点（72 IMAGES/SECOND）。TITAN X与1080TI速度应该差不多。估计4 GPU并没有加速。
https://github.com/yihui-he/resnet-imagenet-caffe/blob/master/resnet_50/logs/resnet_50_resnet_50__2017-01-16_11-41-44.log

我发现CAFFE的多GPU计算并不能加速（对其它模型计算都有这个问题），可能是我电脑主板的原因。也可能是模型本身没有针对多GPU配置。YIHUI HE您发现这个问题了吗？

**Comment by ethanhe42** [comment]
对于大部分model， caffe multi GPU 还是可以加速的。我用的机器有时候会bounded by IO, 这时候multi GPU的确没有用
